//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vmz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Brigade
    {
        public int id { get; set; }
        public int brigadierid { get; set; }
        public string name { get; set; }
        public string description { get; set; }
    
        public virtual User User { get; set; }
    }
}
