//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vmz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JoinBrorTask
    {
        public int idbrortask { get; set; }
        public int idjs { get; set; }
        public int id { get; set; }
    }
}
