//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vmz.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Brigade> Brigade { get; set; }
        public virtual DbSet<JoinBrorTask> JoinBrorTask { get; set; }
        public virtual DbSet<JoinService> JoinService { get; set; }
        public virtual DbSet<ListOfTasks> ListOfTasks { get; set; }
        public virtual DbSet<ListOfUsers> ListOfUsers { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<Profession> Profession { get; set; }
        public virtual DbSet<Service> Service { get; set; }
        public virtual DbSet<Task> Task { get; set; }
        public virtual DbSet<TaskToBrigade> TaskToBrigade { get; set; }
        public virtual DbSet<User> User { get; set; }
    
        public virtual ObjectResult<GetServices_Result> GetServices(Nullable<int> brigadeortaskid)
        {
            var brigadeortaskidParameter = brigadeortaskid.HasValue ?
                new ObjectParameter("brigadeortaskid", brigadeortaskid) :
                new ObjectParameter("brigadeortaskid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetServices_Result>("GetServices", brigadeortaskidParameter);
        }
    
        public virtual ObjectResult<GetTasks_Result> GetTasks(Nullable<int> orderid)
        {
            var orderidParameter = orderid.HasValue ?
                new ObjectParameter("orderid", orderid) :
                new ObjectParameter("orderid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTasks_Result>("GetTasks", orderidParameter);
        }
    
        public virtual ObjectResult<GetUsers_Result> GetUsers(Nullable<int> brigadeid)
        {
            var brigadeidParameter = brigadeid.HasValue ?
                new ObjectParameter("brigadeid", brigadeid) :
                new ObjectParameter("brigadeid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUsers_Result>("GetUsers", brigadeidParameter);
        }
    
        public virtual ObjectResult<ListOfProfessions_Result> ListOfProfessions()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListOfProfessions_Result>("ListOfProfessions");
        }
    
        public virtual ObjectResult<ListOfUsersAdm_Result> ListOfUsersAdm()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListOfUsersAdm_Result>("ListOfUsersAdm");
        }
    
        public virtual int SetUserProf(Nullable<int> uid, Nullable<int> pid)
        {
            var uidParameter = uid.HasValue ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(int));
    
            var pidParameter = pid.HasValue ?
                new ObjectParameter("pid", pid) :
                new ObjectParameter("pid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SetUserProf", uidParameter, pidParameter);
        }
    
        public virtual ObjectResult<GetUserOrders_Result> GetUserOrders(Nullable<int> uid)
        {
            var uidParameter = uid.HasValue ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUserOrders_Result>("GetUserOrders", uidParameter);
        }
    
        public virtual ObjectResult<GetServicesOnBorT_Result> GetServicesOnBorT(Nullable<int> idbort)
        {
            var idbortParameter = idbort.HasValue ?
                new ObjectParameter("idbort", idbort) :
                new ObjectParameter("idbort", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetServicesOnBorT_Result>("GetServicesOnBorT", idbortParameter);
        }
    
        public virtual ObjectResult<GetBrigadeServ_Result> GetBrigadeServ(Nullable<int> idbort)
        {
            var idbortParameter = idbort.HasValue ?
                new ObjectParameter("idbort", idbort) :
                new ObjectParameter("idbort", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetBrigadeServ_Result>("GetBrigadeServ", idbortParameter);
        }
    
        public virtual ObjectResult<GetAllOrdersAndTasks_Result> GetAllOrdersAndTasks()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllOrdersAndTasks_Result>("GetAllOrdersAndTasks");
        }
    
        public virtual ObjectResult<GetBrigadesOrdersAndTasks_Result> GetBrigadesOrdersAndTasks()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetBrigadesOrdersAndTasks_Result>("GetBrigadesOrdersAndTasks");
        }
    
        public virtual ObjectResult<GetOrdersAndTasksCount_Result> GetOrdersAndTasksCount()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetOrdersAndTasksCount_Result>("GetOrdersAndTasksCount");
        }
    
        public virtual ObjectResult<GetTasksAndOName_Result> GetTasksAndOName()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTasksAndOName_Result>("GetTasksAndOName");
        }
    
        public virtual ObjectResult<GetListOfUsersAdm_Result> GetListOfUsersAdm()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetListOfUsersAdm_Result>("GetListOfUsersAdm");
        }
    }
}
