//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vmz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<int> listoftasksid { get; set; }
        public System.DateTime datestart { get; set; }
        public Nullable<System.DateTime> dateend { get; set; }
        public string priority { get; set; }
        public int clientid { get; set; }
    
        public virtual User User { get; set; }
    }
}
