//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vmz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public int listofservices { get; set; }
        public Nullable<System.DateTime> datestart { get; set; }
        public Nullable<System.DateTime> dateend { get; set; }
        public Nullable<int> brigadeid { get; set; }
    
        public virtual Brigade Brigade { get; set; }
        public virtual ListOfTasks ListOfTasks { get; set; }
    }
}
