//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vmz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Brigade = new HashSet<Brigade>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public int professionid { get; set; }
        public string md5 { get; set; }
        public string login { get; set; }
        public int confprofid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Brigade> Brigade { get; set; }
        public virtual ListOfUsers ListOfUsers { get; set; }
        public virtual Profession Profession { get; set; }
    }
}
